name: Keep API Alive

on:
  schedule:
    # Every 1 minutes, GitHub uses UTC time
    - cron: "*/1 * * * *"
  workflow_dispatch: # allows manual run from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping API endpoint
        run: |
          curl -fsS https://pdfchat-ui6g.onrender.com/ping
